"""empty message

Revision ID: b2171d5329da
Revises: b26491277741
Create Date: 2019-10-22 21:44:36.148057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2171d5329da'
down_revision = 'b26491277741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('title', sa.UnicodeText(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'title')
    # ### end Alembic commands ###
